### ISSUE TITLE
Inconsistent behavior with CSS Declaration Sorter

### ISSUE THREAD

**Issue by chalkygames123** [Siilwyn/prettier-plugin-css-order#19]
Given this CSS:

```css
a {
  inset-inline: 0;
  bottom: 0;
  z-index: 0;
}
```

Based on the same sorting order Concentric CSS, CSS Declaration Sorter outputs:

```css
a {
  bottom: 0;
  z-index: 0;
  inset-inline: 0;
}
```

While CSS Order Prettier Plugin outputs:

```
a {
  inset-inline: 0;
  bottom: 0;
  z-index: 0;
}
```

Minimal reproduction: https://github.com/chalkygames123/repro-prettier-plugin-css-order-inconsistency
