### ISSUE TITLE
CSS property 'grid-cap' not in correct alphabetical order

### ISSUE THREAD

**Issue by Kristjan-Kiolein** [Siilwyn/prettier-plugin-css-order#20]
How to reproduce:
 * `ng new angular-tour-of-heroes` selecting SCSS when prompted
 * `npm install prettier --save-dev`
 * `npm install postcss prettier-plugin-css-order --save-dev`
 * Add prettier properties
   ```json
    {
      "order": "alphabetical"
    }
   ```
 * Add following styles to scss file
   ```css
   .grid-properties {
     color: blue;
     grid-gap: 1rem;
   }
   ```
 * `prettier --write src`
 
 Now the resulting scss file looks like this:
 ```css
.grid-properties {
   grid-gap: 1rem;
   color: blue;
}
 ```
 
A workaround would be to use the css3 property `gap` instead of `grid-gap`
