### ISSUE TITLE
pre-commit hook configuration

### ISSUE THREAD

**Issue by LuckyType** [Siilwyn/prettier-plugin-css-order#32]
I tried to add this plugin to our pre-commit-config.yaml like so:

 ```yaml
   - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.3
    hooks:
      - id: prettier
        additional_dependencies:
          - prettier@3.0.3
          - 'prettier-plugin-css-order'
```
After successful installation the Hook seems to fail because of the definition within the prettier config:
`[error] Cannot find package 'prettier-plugin-css-order' imported from /.../noop.js`

My config:
```
{
  "tabWidth": 2,
  "overrides": [
    {
      "files": "*.js",
      "options": {
        "tabWidth": 4,
        "printWidth": 200
      }
    }
  ],
  "plugins": [
    "prettier-plugin-css-order"
  ]
}
```
When removing `"plugins"` from the config, prettier runs through just fine, but obviously not using the plugin.

Any idea?
